version: '3.8'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8.0.28
    container_name: lecture-mysql
    environment:
      MYSQL_DATABASE: lecture
      MYSQL_USER: lecture-user
      MYSQL_PASSWORD: lecture-password
      MYSQL_ROOT_PASSWORD: root-password
    ports:
      - "3306:3306"